### ISSUE TITLE
Game Does Not Mount

### ISSUE THREAD

**Issue by ClydeFrog04** [elraccoone/react-unity-webgl#147]
I can't seem to get my game to mount. I am using Unity 2020 with the most recent react-unity-webgl install. I have my configuration setup exactly as it is in the readme, but when I run my react app I'm running into two different console logs, and a blank screen. 
![image](https://user-images.githubusercontent.com/31398520/108640647-2dd7e600-7458-11eb-8374-f55fe0162178.png)
I am not sure if this is a known bug, or if there is something I'm missing! 
Here is my filesystem, and setup in my react app. I want to note that I tried with and without the gzipped files, once with them and once extracted and without the extension in my react app.
![image](https://user-images.githubusercontent.com/31398520/108640691-6b3c7380-7458-11eb-9560-8bd3aa73a3e3.png)
![image](https://user-images.githubusercontent.com/31398520/108640706-78596280-7458-11eb-83e0-a93aadf89771.png)

As far as I can tell it's set up properly, just can't work out this issue!

**Comment by ClydeFrog04** [comment]
I don’t think this is a duplicate, issue #57 looks to be for unity 2019, I am using unity 2020 which does not have a build.json not a unityContent, rather it uses a unityContext which does not show a build.json

**Comment by jeffreylanters** [comment]
It's the same concept, the file the module is looking for does not exist on the current path. Your server returns an 404 page, which your browser interpets as a JavaScript file. Since the HTML 404 page starts with `<html>...` the `unexpected token <` error is thrown because it is not valid JavaScript.

**Comment by ClydeFrog04** [comment]
@jeffreylanters that makes sense. It steered me in the right direction at least. I have my file structure perfectly in line with how the docs are, my Unity component and Unity context are perfect. The problem was, the build folder needs to be named "build" and not "Build". "Build" is how the folder is named from Unity when you build the project so it has to be renamed. My game is now loading and working in my react app!

**Comment by jeffreylanters** [comment]
Ah I see, casing can be misleading, most server require the exact casing. Keep in mind that Git does not detect casing changes as actual changes in your repository. So make sure your project in GitHub project is in sync with your local Git repo. Otherwise you could run into the same problem when cloning your project. I'm glad your project is running, happy coding!
