### ISSUE TITLE
using  unityContent.send does not work inside react hook "useeffect" 

### ISSUE THREAD

**Issue by DanielAudaptic** [elraccoone/react-unity-webgl#79]
**Describe the bug**
using  unityContent.send does not work inside react hook "useeffect". Method is not called in unity.

**To Reproduce**
    React.useEffect(() => {
        unityContent.send(
            "TestObject",
            "TestMethod",
            10
        );
    }, [updatedParameter]);

**Expected behavior**
method should be called in unity

**Desktop (please complete the following information):**
 - Chrome
 - Unity 2019.2

**Comment by jeffreylanters** [comment]
I havent used React Hooks yet. But it. seems like useEffect is just an arrow functions, it shouldn't matter what you're invoking inside it, right? Are you sure a console log right there shows up in the inspector? Have you tried it outside off a hook?

**Comment by DanielAudaptic** [comment]
Using the below code, if the button is pressed the "clicked" is printed in the console, and the method is called in unity. But if the useEffect is triggered, the "clicked" is printed but the method in unity is not called. 
And after useEffect is called once, and if I then click the button again, the "clicked' is printed but the method is no longer called in unity.


-------------------------------------------------------------------------------------------

const UnityContainer: React.FC<IUnityContainerProps> = ({ appState, scenarioState, unityContent }) => {

    React.useEffect(() => {
        onClick();
    }, [scenarioState]);


    const onClick = () => {
        unityContent.send(
            "Cube",
            "TestMethod",
            10
        );

        console.log("clicked");
    }

 
    return <div>
        <button onClick={onClick}>Press!</button>
        <Unity unityContent={unityContent} />
        </div>

    
};


export default UnityContainer;

**Comment by DanielAudaptic** [comment]
Looks like the same issue as: https://github.com/elraccoone/react-unity-webgl/issues/74

**Comment by GildedHonour** [comment]
Is help needed on this?

**Comment by AdhamMoussa** [comment]
I checked #74 and I think the problem is initializing `unityContent` inside the component.
I believe this should be done outside of the component to prevent re-initializing it on every re-render.
If you're doing the same, this maybe the problem u have
(check the parent component that is providing `unityContent` to `UnityContainer`)

**Comment by dm0141e** [comment]
@AdhamMoussa, you are not quite right, this can be fixed in the library.
In UnityContent.ts file you can see` if (this.unityInstance != null) {}` in "setFullscreen" and "send" methods. In this situation `unityInstance === null` (because if `unityContent` created in functional component, it's recreating after rerender and `componentDidMount` in `Unity` component not called repeatedly).

One of ways to fix this:
1) Create `this.unityInstance` for memoization in Unity.ts file in `componentDidMount` hook. 
2) Create `componentDidUpdate` hook and in `componentDidMount `and `componentDidUpdate` provide memo instance to `unityContent`

**Comment by DanielAudaptic** [comment]
@AdhamMoussa  your are correct! that solved my issues, thank yo ujso much for the assitans!
