### ISSUE TITLE
Beginner Help - can't launch a website by npm start

### ISSUE THREAD

**Issue by ManaAura** [elraccoone/react-unity-webgl#89]
**Describe the bug**
I'm new to react. From the official react guide, I tested out my website from the localhost, simply by typing the command "npm start". However, I am unable to do that from following the guide on this repo.

Please guide me the exact steps I need to do after I [npm install react-unity-webgl] in order for me to see a "demo website" on my chrome & thanks

**To Reproduce**
Followed the guide on the main page:
1. npm install react-unity-webgl

Followed the guide on the contribution page
1. fork the master
2. npm install

I Also tried to fork the react-webgl-test, but none of the guides above showed a demo website on chrome. It's either "missing package.json" error or just a gray message of "start compilation" from the console.

**Expected behavior**
1. npm install react-unity-webgl
2. cd src
3. npm start demo.js

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jeffreylanters** [comment]
Hello. Are you also new to Node and NPM? You should not fork this repository if you want to get started with this module. The module is a dependency which you cannot use by itself, you'll React project first. Do you have a working and running React project?

**Comment by ManaAura** [comment]
I'm also very new to NPM. & node. I do have a working and running React project (the official react tutorial project).

**Comment by paullam328** [comment]
well, you need a Node server to install Node Modules.  React-unity-webgl is a Node Module.
Node server is created within a React project, so that you would need to create a React project:

To create a project:
npx create-react-app my-app
cd my-app
npm start

The server would automatically start at localhost:3000 by default.

Then, in your terminal, type: npm install react-unity-webgl

 to use this module well, you need to reference the port of the localhost in package.json.  Put your build within the public folder to access them.

In package.json, insert:
  "proxy": "http://localhost:3000"

Then, place your build in the Public folder, as node server accesses assets from public instead of root directory.

After that you just need to read the very simple react-unity-webgl documentary, and you are good to go
